/* ============================================================
   04b_bulk_data.sql
   Adds bulk synthetic data ON TOP of 04_sample_data.sql's
   curated 10 customers / 18 products / 18 orders (those IDs
   stay untouched — every demo in 06-10 that references them by
   ID still works). Scales to:
     Customers ~5,000   Categories 10   Products ~500
     Orders    ~100,000 OrderItems ~250,000
     Payments  ~80,000  Shipments  ~70,000
   Pure set-based generation (tally table + modulo arithmetic),
   no cursors/loops. Idempotent — re-running after a first
   successful run is skipped automatically.
   ============================================================ */

USE ECommerceOrderDB;
GO
SET NOCOUNT ON;

/* Guard: curated data only ever has 10 customers. If more exist,
   bulk data already ran — do nothing rather than double it up. */
IF (SELECT COUNT(*) FROM dbo.Customers) > 10
BEGIN
    PRINT 'Bulk data already present — skipping. Re-run 01-04 first to reset.';
    RETURN;
END

/* ----------------------------------------------------------
   Driver table: 200,000 consecutive integers, generated by
   cross-joining doubling CTEs (no recursion limit issues).
   ---------------------------------------------------------- */
IF OBJECT_ID('tempdb..#Tally') IS NOT NULL DROP TABLE #Tally;

;WITH
E1(N) AS (SELECT N FROM (VALUES (1),(1),(1),(1),(1),(1),(1),(1),(1),(1)) AS X(N)),
E2(N) AS (SELECT 1 FROM E1 a CROSS JOIN E1 b),   -- 100
E4(N) AS (SELECT 1 FROM E2 a CROSS JOIN E2 b),   -- 10,000
E8(N) AS (SELECT 1 FROM E4 a CROSS JOIN E4 b)     -- 100,000,000
SELECT TOP (200000) N = ROW_NUMBER() OVER (ORDER BY (SELECT NULL))
INTO #Tally
FROM E8;

CREATE UNIQUE CLUSTERED INDEX IX_Tally_N ON #Tally (N);

/* ----------------------------------------------------------
   1. Categories — 4 more, on top of the curated 6 (IDs 7-10).
   ---------------------------------------------------------- */
INSERT INTO dbo.Categories (CategoryName, Description) VALUES
('Toys & Games',            'Kids toys, board games and puzzles'),
('Automotive Accessories',  'Car care and accessory products'),
('Office Supplies',         'Stationery and workspace essentials'),
('Pet Supplies',            'Food and accessories for pets');

/* ----------------------------------------------------------
   2. Products — 482 more (IDs 19-500), spread across all
      10 categories, random price/stock/reorder, ~3% inactive.
   ---------------------------------------------------------- */
INSERT INTO dbo.Products (ProductName, CategoryID, UnitPrice, StockQuantity, ReorderLevel, IsActive)
SELECT
    CONCAT(c.CategoryName, ' Item ', t.N),
    c.CategoryID,
    CAST(99 + (ABS(CHECKSUM(NEWID())) % 9900) AS DECIMAL(10,2)),
    ABS(CHECKSUM(NEWID())) % 400,
    10 + (ABS(CHECKSUM(NEWID())) % 20),
    CASE WHEN ABS(CHECKSUM(NEWID())) % 100 < 3 THEN 0 ELSE 1 END
FROM #Tally t
CROSS APPLY (
    SELECT TOP (1) CategoryID, CategoryName FROM dbo.Categories ORDER BY NEWID()
) c
WHERE t.N <= 482;

/* ----------------------------------------------------------
   3. Customers — 4,990 more (IDs 11-5000). Email suffixed with
      the tally number so it stays UNIQUE even with repeated
      name combinations.
   ---------------------------------------------------------- */
INSERT INTO dbo.Customers (FirstName, LastName, Email, Phone, City, State, RegisteredDate)
SELECT
    fn.FirstName,
    ln.LastName,
    CONCAT(LOWER(fn.FirstName), '.', LOWER(ln.LastName), t.N, '@example.com'),
    CONCAT('9', CAST(100000000 + (ABS(CHECKSUM(NEWID())) % 899999999) AS VARCHAR(9))),
    loc.City,
    loc.State,
    DATEADD(DAY, -(ABS(CHECKSUM(NEWID())) % 730), CAST(GETDATE() AS DATE))
FROM #Tally t
CROSS APPLY (SELECT TOP (1) FirstName FROM (VALUES
    ('Aarav'),('Vivaan'),('Aditya'),('Vihaan'),('Arjun'),('Reyansh'),('Ayaan'),('Krishna'),
    ('Ishaan'),('Rohan'),('Priya'),('Ananya'),('Diya'),('Saanvi'),('Aadhya'),('Myra'),
    ('Anika'),('Kavya'),('Riya'),('Sneha')) AS X(FirstName) ORDER BY NEWID()) fn
CROSS APPLY (SELECT TOP (1) LastName FROM (VALUES
    ('Shah'),('Mehta'),('Patel'),('Nair'),('Iyer'),('Rao'),('Verma'),('Desai'),
    ('Kapoor'),('Menon'),('Pillai'),('Reddy'),('Gupta'),('Joshi'),('Kulkarni'),('Bose')) AS X(LastName) ORDER BY NEWID()) ln
CROSS APPLY (SELECT TOP (1) City, State FROM (VALUES
    ('Surat','Gujarat'), ('Ahmedabad','Gujarat'), ('Mumbai','Maharashtra'), ('Pune','Maharashtra'),
    ('Chennai','Tamil Nadu'), ('Coimbatore','Tamil Nadu'), ('Bengaluru','Karnataka'),
    ('Hyderabad','Telangana'), ('Delhi','Delhi'), ('Kochi','Kerala'), ('Jaipur','Rajasthan'),
    ('Lucknow','Uttar Pradesh'), ('Kolkata','West Bengal'), ('Bhopal','Madhya Pradesh'),
    ('Chandigarh','Punjab')) AS X(City, State) ORDER BY NEWID()) loc
WHERE t.N <= 4990;

/* ----------------------------------------------------------
   4. Orders — 99,982 more (IDs 19-100,000). CustomerID and
      OrderDate random; OrderStatus weighted to look realistic.
   ---------------------------------------------------------- */
DECLARE @CustomerCount INT = (SELECT COUNT(*) FROM dbo.Customers);
DECLARE @StartDate     DATE = DATEADD(YEAR, -2, CAST(GETDATE() AS DATE));
DECLARE @DaySpan       INT  = DATEDIFF(DAY, @StartDate, CAST(GETDATE() AS DATE));

INSERT INTO dbo.Orders (CustomerID, OrderDate, OrderStatus, TotalAmount)
SELECT
    (ABS(CHECKSUM(NEWID())) % @CustomerCount) + 1,
    DATEADD(SECOND, ABS(CHECKSUM(NEWID())) % (@DaySpan * 86400), CAST(@StartDate AS DATETIME2(0))),
    CASE
        WHEN r.Roll < 55 THEN 'Delivered'
        WHEN r.Roll < 70 THEN 'Shipped'
        WHEN r.Roll < 80 THEN 'Confirmed'
        WHEN r.Roll < 92 THEN 'Pending'
        ELSE 'Cancelled'
    END,
    0
FROM #Tally t
CROSS APPLY (SELECT ABS(CHECKSUM(NEWID())) % 100 AS Roll) r
WHERE t.N <= 99982;

/* ----------------------------------------------------------
   5. OrderItems for the new orders — 1 to 4 lines each,
      ProductID picked by a deterministic formula on OrderID so
      the 4 possible lines for any one order can never collide
      (97 * lineNumber gives 4 distinct residues mod 500 —
      gcd(97,500)=1 — so UNIQUE(OrderID,ProductID) is guaranteed).
   ---------------------------------------------------------- */
DECLARE @ProductCount INT = (SELECT COUNT(*) FROM dbo.Products);

INSERT INTO dbo.OrderItems (OrderID, ProductID, Quantity, UnitPrice)
SELECT
    o.OrderID,
    p.ProductID,
    ((o.OrderID + ln.LineNumber) % 5) + 1,
    p.UnitPrice
FROM dbo.Orders o
CROSS JOIN (VALUES (1),(2),(3),(4)) AS ln(LineNumber)
JOIN dbo.Products p
    ON p.ProductID = (((o.OrderID * 37) + ln.LineNumber * 97) % @ProductCount) + 1
WHERE o.OrderID > 18
  AND ln.LineNumber <= ((o.OrderID % 4) + 1);

/* Recalculate every order's total (same logic as 04_sample_data.sql;
   trigger in 09_triggers.sql takes over once it exists). */
UPDATE o
SET o.TotalAmount = x.SumTotal
FROM dbo.Orders o
CROSS APPLY (
    SELECT ISNULL(SUM(LineTotal), 0) AS SumTotal
    FROM dbo.OrderItems
    WHERE OrderID = o.OrderID
) x;

/* ----------------------------------------------------------
   6. Payments — for any Confirmed/Shipped/Delivered order that
      doesn't already have one (curated orders already do).
   ---------------------------------------------------------- */
INSERT INTO dbo.Payments (OrderID, PaymentDate, PaymentMethod, AmountPaid, PaymentStatus)
SELECT
    o.OrderID,
    DATEADD(HOUR, 2, o.OrderDate),
    CASE o.OrderID % 5
        WHEN 0 THEN 'CreditCard' WHEN 1 THEN 'DebitCard' WHEN 2 THEN 'UPI'
        WHEN 3 THEN 'NetBanking' ELSE 'CashOnDelivery'
    END,
    o.TotalAmount,
    'Completed'
FROM dbo.Orders o
WHERE o.OrderStatus IN ('Confirmed', 'Shipped', 'Delivered')
  AND NOT EXISTS (SELECT 1 FROM dbo.Payments pay WHERE pay.OrderID = o.OrderID);

/* ----------------------------------------------------------
   7. Shipments — for any Shipped/Delivered order that doesn't
      already have one.
   ---------------------------------------------------------- */
INSERT INTO dbo.Shipments (OrderID, Carrier, ShipmentStatus, ShippedDate, DeliveredDate, TrackingNumber)
SELECT
    o.OrderID,
    'BlueDart Express',
    CASE o.OrderStatus WHEN 'Delivered' THEN 'Delivered' ELSE 'In Transit' END,
    DATEADD(DAY, 1, o.OrderDate),
    CASE o.OrderStatus WHEN 'Delivered' THEN DATEADD(DAY, 4, o.OrderDate) ELSE NULL END,
    CONCAT('TRK', FORMAT(o.OrderID, '00000'))
FROM dbo.Orders o
WHERE o.OrderStatus IN ('Shipped', 'Delivered')
  AND NOT EXISTS (SELECT 1 FROM dbo.Shipments sh WHERE sh.OrderID = o.OrderID);

DROP TABLE #Tally;

/* ---- Summary ---- */
SELECT 'Customers' AS TableName, COUNT(*) AS RowCount FROM dbo.Customers
UNION ALL SELECT 'Categories', COUNT(*) FROM dbo.Categories
UNION ALL SELECT 'Products', COUNT(*) FROM dbo.Products
UNION ALL SELECT 'Orders', COUNT(*) FROM dbo.Orders
UNION ALL SELECT 'OrderItems', COUNT(*) FROM dbo.OrderItems
UNION ALL SELECT 'Payments', COUNT(*) FROM dbo.Payments
UNION ALL SELECT 'Shipments', COUNT(*) FROM dbo.Shipments;
GO
